# Generated by Django 4.2.3 on 2024-11-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='Philippines', max_length=100),
        ),
    ]
